/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'paul' at '25/09/15 14:27' with Gradle 2.1
 *
 * @author paul, @date 25/09/15 14:27
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
