/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'paul' at '25/09/15 14:27' with Gradle 2.1
 *
 * @author paul, @date 25/09/15 14:27
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
